accounts/urls.py
from django.urls import re_path, path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r"^login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    re_path(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    re_path(r"^signup/$", views.SignUp.as_view(), name="signup"),
    re_path(r"^home/$", views.home, name=""),
    path('profile-update/',views.updateProfile, name='profile-update'),
    path('follow-unfollow/<int:pk>/',views.userFollowUnfollow, name="follow-unfollow"),
    path('<str:username>/', views.profile, name='profile'),
    path('search/asame/', views.search_view, name='search'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/', views.notifications_update_view, name='notifications-update'),
    path('<str:username>/notifications/count/', views.notifications_unread_count_view, name='notifications-count'),
    path('like/post',views.like_view,name='like'),
    path('p/<slug:slug>/', views.post_detail_view, name="post-detail"),
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'),
]

asame/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^logged/$", views.LoggedPage.as_view(), name="logged"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r'^spotify/', include('spotify.urls', namespace='spotify')),


]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill,Transpose
from taggit.managers import TaggableManager
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.
# class User(auth.models.User, auth.models.PermissionsMixin):
#     def _str_(self):
#         return f'{self.username}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25,blank=True)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    image_thumbnail_user = ImageSpecField(source='image',
                                      processors=[Transpose(),ResizeToFill(170, 170)],
                                      format='JPEG',
                                      options={'quality': 100})

    description = models.CharField(max_length=100, blank=True)
    follows = models.ManyToManyField(User,related_name="follows",blank=True)
    followers = models.ManyToManyField(User,related_name="followers",blank=True)
    def _str_(self):
        return f"{self.user.username}'s Profile"

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True,unique=True,max_length=111)
    content =  models.TextField()
    image =  models.ImageField(upload_to='post_images')
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[
                                        Transpose(),
                                        ResizeToFill(1000, 500)
                                        ],
                                      format='JPEG',
                                      options={'quality': 70})

    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes',blank=True)
    tagged_users = models.ManyToManyField(User, related_name='tagged_users',blank=True)

    @property
    def total_likes(self):
        return self.likes.count()

    def _str_(self):
        return self.title


    def get_absolute_url(self):
        return reverse('accounts:post-detail', kwargs={'slug': self.slug})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def _str_(self):
        return self.comment

class Notification(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE, related_name='receiver')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,null=True)
    action = models.CharField(max_length=50, blank=True)
    read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=timezone.now)

@receiver(post_save,sender=Post)
def post_mentioned_notify(sender, instance, *args, **kwargs):
    sender = User.objects.get(pk=instance.author.pk)
    post = Post.objects.get(pk=instance.pk)
    string = instance.content
    poss_users = [i  for i in string.split() if i.startswith("@")]
    poss_users_list = []
    for user in poss_users:
        poss_users_list.append(user[1:])

    for username in poss_users_list:
        try:
            get_user = User.objects.get(username=username)
        except:
            continue
        if get_user in instance.tagged_users.all():
            continue
        elif get_user == sender:
            continue
        else:
            instance.tagged_users.add(get_user)
            notify = Notification.objects.create(sender=sender,receiver=get_user,post=post,action="mentioned you in post")


@receiver(post_save,sender=Comment)
def comment_added_notify(sender, instance, *args, **kwargs):
    sender = User.objects.get(pk=instance.author.pk)
    post = Post.objects.get(pk=instance.post.pk)
    receiver = User.objects.get(pk=instance.post.author.pk)
    if receiver == sender:
        pass
    else:
        notify = Notification.objects.create(sender=sender,receiver=receiver,post=post,action="commented on your post")


@receiver(pre_save,sender=Post)
def sulg_generator(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title+" "+str(sender.objects.count()))

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment, Post, Profile
from django import forms
from taggit.managers import TaggableManager


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title','content','image']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    camps = TaggableManager(verbose_name=u'Pasta')
    class Meta:
        model = Profile
        fields = ['image','name','description']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404,redirect
from django.db.models import Q
from django.http import HttpResponse,JsonResponse
try:
    from django.utils import simplejson as json
except ImportError:
    import json
import random

from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Comment, Notification, Profile
from .forms import CommentForm, PostForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from . import forms



def home(request):
    return render(request, "accounts/index.html")


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

@login_required
def profile(request, username=None):
    user = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=user).order_by('-id')
    post_count = post_list.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 4)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'user_id': user,
        'post_count': post_count,
    }
    template_name = 'accounts/profile.html'

    return render(request, template_name, context)

@login_required
def updateProfile(request):
    if request.method == 'POST':
        User_form = UserUpdateForm(request.POST, instance=request.user)
        Profile_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if User_form.is_valid() and ProfileForm.is_valid():
            User_form.save()
            Profile_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile', username=request.user.username)
        else:
            messages.error(request, f'Username already exists or in use!')
            return redirect('profile-update')
    else:
        User_form = UserUpdateForm(instance=request.user)
        Profile_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'User_form': User_form,
            'Profile_form': Profile_form,
        }
        template_name = 'accounts/update_profile.html'

        return render(request, template_name, context)


@login_required
def userFollowUnfollow(request, pk=None):
    current_user = request.user
    other_user = User.objects.get(pk=pk)

    if other_user not in current_user.profile.follows.all():
        current_user.profile.follows.add(other_user)
        other_user.profile.followers.add(current_user)

        notify = Notification.objects.create(sender=current_user, receiver=other_user, action="started following you.")

    else:
        current_user.profile.follows.remove(other_user)
        other_user.profile.followers.remove(current_user)
    return redirect('profile', username=other_user.username)


@login_required
def post_create_view(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author=request.user
            post.save()
            context = {'url':post.get_absolute_url()}
            return HttpResponse(json.dumps(context), content_type='application/json')

    else:
        form = PostForm()
        context = {
            'form': form,
        }
        return render(request,'accounts/post_form.html',context)


def post_detail_view(request,slug=None):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post=post
            comment.author=request.user
            comment.save()
            return redirect('accounts:post-detail', slug=post.slug)
    else:
        form = CommentForm()

        comments = Comment.objects.filter(post=post).order_by('-id')
        context = {'post':post,'form':form,'comments':comments}

    return render(request,'accounts/post_detail.html',context)


@login_required
def post_update_view(request,pk):
    post1 = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES,instance=post1)
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
            ctx = {'url':post.get_absolute_url()}
            return HttpResponse(json.dumps(ctx), content_type='application/json')
    else:
        post = get_object_or_404(Post,pk=pk)
        form = PostForm(instance = post)
        context = {
            'form': form,
            'post':post,
        }
        return render(request,'accounts/post_form_update.html',context)

@login_required
def post_delete_view(request, pk=None):
    context = {}
    post = get_object_or_404(Post,pk=pk)

    if request.method =="POST":
        if post.author == request.user:
            post.delete()
            return redirect('accounts:profile', username=request.user.username)
    context = {"post":post}
    return render(request,'accounts/post_confirm_delete.html',context)



@login_required
def search_view(request):

    message = ""
    post_list = Post.objects.all().order_by('-pk');
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 4)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        try:
            search_input = request.POST.get('search')
            result_posts = Post.objects.filter(Q(title_icontains=search_input)|Q(content_icontains=search_input))
            users = User.objects.filter(Q(username__iexact=search_input))

            # first condition :  users-0
            if users.count() == 0:
                message = "No results found for: " + search_input
                context = {'message':message,'posts':posts,'search_input':search_input}
                return render(request,'accounts/search.html',context)


            # second condition :user: yes
            else:
                context = {'users':users,'search_input':search_input}
                return render(request,'accounts/search.html',context)

        except:
            message = "Unexpected Error Occured!"
            context = {'message':message}
            return render(request,'accounts/search.html',context)
    else:
        flag = True
        context = {'posts':posts,'flag':flag}
        return render(request,'accounts/search.html',context)


@login_required
@require_POST
def like_view(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('pk', None)
        post = get_object_or_404(Post, pk=pk)

        if post.likes.filter(id=user.id).exists():
            post.likes.remove(user)
            like = False
            post_id = '#like'+str(post.id)
        else:
            post.likes.add(user)
            like = True
            post_id = '#like'+str(post.id)

    ctx = {'likes_count': post.total_likes,'like':like,'post_id':post_id}
    return HttpResponse(json.dumps(ctx), content_type='application/json')

@login_required
def notifications_view(request,username=None):
    user = get_object_or_404(User,username=username)
    notifications = Notification.objects.filter(receiver=user).order_by('-timestamp')
    page = request.GET.get('page', 1)
    paginator = Paginator(notifications, 6)
    try:
        notifications = paginator.page(page)
    except PageNotAnInteger:
        notifications = paginator.page(1)
    except EmptyPage:
        notifications = paginator.page(paginator.num_pages)

    return render(request,'accounts/notifications.html',{'notifications':notifications})

@login_required
def notifications_update_view(request,username=None):
    user = get_object_or_404(User,username=username)
    if user == request.user:
        notifications = Notification.objects.filter(receiver=user)
        for notification in notifications.all():
            if notification.read == False:
                notification.read = True
                notification.save()
        return HttpResponse('')


@login_required
def notifications_unread_count_view(request,username=None):
    user = get_object_or_404(User,username=username)
    if user == request.user:
        notifications = Notification.objects.filter(receiver=user)
        count = 0
        for notification in notifications.all():
            if notification.read == False:
                count = count+1
        data = {
            'count':count
        }
        return JsonResponse(data)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

<div class="container">
  <br>
  <h1 style="text-align:center;">Login</h1>
  <form method="POST">
    {% csrf_token %}
    <div style="width: 300px; margin:auto;">
      {% bootstrap_form form %}
      <br>
      <input type="submit" value="Login" class="btn btn-primary">
    </div>


  </form>
</div>


{% endblock %}

accounts/templates/accounts/notifications.html
{% extends "base.html" %}
{% block title %}<title> @{{request.user.username}}'s notifications</title>{% endblock %}

{% block content %}
      <div class="content-section overflow-auto infinite-container">
          <br>
        <h1 style="text-align:center;">Notifications</h1>
        {% for notification in notifications %}
          {% if notification.read %}
          <p class="notification-list-items-read infinite-item">
          {%else%}
          <p class="notification-list-items-unread infinite-item">
          {% endif %}

            <a href="{% url 'profile' notification.sender.username %}" style="text-decoration: blink;">{{notification.sender.username}}</a> {{notification.action}}
            {% if notification.post %}
             <span class="post-title-notify"><a href="{% url 'accounts:post-detail' notification.post.slug %}">"{{notification.post.title}}".</a></span>
            {% endif %}
             <br><small>({{notification.timestamp|date:"D, d M, g:i a"}})</small>
          </p>
        {% empty %}
        <p class="notification-list-items-unread" style="text-align:center;">No notifications yet!</p>
        {% endfor %}
      </div>

      <div class="loading" style="display: none;">
        Loading...
      </div>
      {% if notifications.has_next %}
        <a class="infinite-more-link" style="display: none;" href="?page={{ notifications.next_page_number }}">More</a>
      {% endif %}

{% endblock content %}
{% block script %}
        <script>
        $( document ).ready(function(){
            $.ajax({
                url: "{% url 'accounts:notifications-update' request.user.username %}",
                type: 'get',
                success: function(data){
                },
                error: function (xhr, ajaxOptions, thrownError) {
                  }
            });
        });
        </script>
        <script>
          var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
              $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
              $('.loading').hide();
            }
          });
      </script>

{% endblock %}

accounts/templates/accounts/post_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block meta %}
  <meta name="description" content={{post.title}}>
{% endblock %}


{% block title %}<title> {{post.title}} - Asame</title>{% endblock %}

{% block content %}
<div class="container">
  <article class="content-section-details">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2"
           href="{% url 'accounts:profile' post.author.username %}"><span class="link-style-none">Post by: </span> {{ post.author }}
        </a>
        <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>

      </div>
      {% if post.author == user %}
          <div>
            <a class="btn btn-outline-secondary btn-success mt-1 mb-1"
               href="{% url 'accounts:post-update' post.id %}">Update
            </a>
            <a class="btn btn-outline-danger btn-danger mt-1 mb-1"
               href="{% url 'accounts:post-delete' post.id %}">Delete
            </a>
          </div>

      {% endif %}
    </div>

  </article>
  <article class="media">
    <div class="media-body">
      <h1 class="article-title">{{ post.title }}</h1>
      <hr>
      <img class="post-image-detail" src="{{post.image.url}}">
      <br>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <div class="post-applause-details read-more">
              <p id="like-count">{{post.likes.count}}</p>
              <p id="like-count-2" style="display: none;"></p>
              <a href="" name="{{post.id}}" id="like{{post.id}}" class="like">
              <span class="glyphicon glyphicon-heart"> </span> Likes
              </a>


  </div>
  {% if user.is_authenticated %}
  <div class="article-form">
    <form method="POST" class="">{% csrf_token %}
      {{form | crispy}}
      <button type="submit" class="btn btn-primary" style="float: right;">Post</button>
    </form>
  </div>
  {% endif %}
  <br>
  <div class="comments">
  <p>{{comments.count}} Comments</p>
  {% for comment in comments %}
  <div class="comments-inside">
    <a class="link-style-none" href="{% url 'profile' comment.author.username %}">
      <img class="rounded-circle article-img-comment" src="{{comment.author.profile.image_thumbnail_user.url}}" width="55">
    </a>
    <article class="media content-section-blue">
      <div class="media-body">
        <small>{{ comment.author }} - {{comment.date_posted}}</small>
        <p class="article-content">{{ comment.comment}}</p>
      </div>
    </article>
  </div>

  {% endfor %}
  </div>


</div>


{% endblock content %}

{% block script %}
{% if user in post.likes.all %}
<script>
    $(document).ready(function () {
      $('#unliked').hide()
    });
</script>
{% else %}
<script type="text/javascript">
    $(document).ready(function () {
      $('#liked').hide()
    });
</script>
{% endif %}

<script>
$(document).ready(function () {
$('.like').click(function(event){
      event.preventDefault();
      $.ajax({
               type: "POST",
               url: "{% url 'accounts:like' %}",
               data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                      if (response.like) {
                        $('#liked').show();
                        $('#unliked').hide();
                        $('#like-count').text(response.likes_count);

                      } else {
                        $('#liked').hide();
                        $('#unliked').show();
                        $('#like-count').text(response.likes_count);
                      }
                },

                error: function(rs, e) {
                       alert('Poor network try again or refresh the page.');


                }
          });
    });
});
</script>


<script type="text/javascript">
  $(document).ready(function(){
    $(".article-content").each(function(data){
      var UserReg = /(^|\s)@([\w\d-]+)/g
      var NewText = $(this).html().match(UserReg, "$1<a href='/$2/'>@$2</a>")
      var NewText = $(this).html().replace(UserReg, "$1<a href='/$2/'>@$2</a>")
      $(this).html(NewText)
    })
  })
</script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".article-content").each(function(data){
      var LinkReg = /(https?:\/\/[^\s]+)/g;
      var LinkText = $(this).html().match(LinkReg)
      var LinkText = $(this).html().replace(LinkReg, "<a href="+LinkText+">"+LinkText+"</a>")
      $(this).html(LinkText)
    })
  })
</script>
{% endblock %}

accounts/templates/accounts/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
 {% block title %}
   <title>Add post * @{{request.user.username}}</title>
 {% endblock %}
{% block content %}
<div class="container">
  <div class="content-section">
      <form action="{% url 'accounts:post-create' %}" method="POST" id="post-form">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Add Post</legend>
              {{form | crispy}}
          </fieldset>
          <div class="form-group" style="display: flex;justify-content: flex-end;">
              <button class="btn btn-info btn-sm" type="submit" id="form-submit" style="padding: 5px 25px">Post</button>
          </div>
      </form>
      <div class="loading-bar" style="display: none;">
          <div class="progress">
              <div id="progress-bar" class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" aria-valuenow="0"aria-valuemin="0" aria-valuemax="100" style="width: 0%">0%</div>
          </div>
      </div>

  </div>
</div>

{% endblock content %}

{% block script %}
<script>
    $('#post-form').on('submit', function(event){
        event.preventDefault();
        $form = $(this)
        var formData = new FormData(this);
        $.ajax({
            xhr : function(){
                var xhr = new window.XMLHttpRequest();
                xhr.upload.addEventListener('progress',function(event){
                    if (event.lengthComputable){

                        var percent = Math.round((event.loaded/event.total)*100);
                        $('.loading-bar').show();
                        $('#post-form').hide();
                        $('#progress-bar').attr('aria-valuenow',percent).css('width',percent+'%').text(percent+'%')
                    }
                });
                return xhr;
            },
            url : "{% url 'accounts:post-create' %}",
            type : "POST",
            data: formData,
            processData: false,
            contentType: false,
            success : function(json) {
              window.location.href=(json.url);
            },

            error : function(xhr,errmsg,err) {
            }
        });
    });

</script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#div_id_image').children('div').addClass('currentPhoto');
        $('.currentPhoto').children('a').hide();
        let isTextNode = (_, el) => el.nodeType === Node.TEXT_NODE;
        $('.currentPhoto').contents().filter(isTextNode).remove();
        var img = document.createElement("IMG");
        img.src = '{{ post.image_thumbnail_detail.url }}';
        img.setAttribute('class', 'post-img-update');
        $('.currentPhoto').prepend('<br>Change Image');
        $('.currentPhoto').prepend(img);
    });
</script>

{% endblock %}

accounts/templates/accounts/post_form_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
 {% block title %}
   <title>Update post * @{{request.user.username}}</title>
 {% endblock %}
{% block content %}
<div class="container">
  <div class="content-section">
      <form action="{% url 'accounts:post-update' post.pk%}" method="POST" id="post-form">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Update Post</legend>
              {{form | crispy}}
          </fieldset>
          <div class="form-group" style="display: flex;justify-content: flex-end;">
              <button class="btn btn-info btn-sm" type="submit" id="form-submit" style="padding: 5px 25px">Update</button>
          </div>
      </form>
      <div class="loading-bar" style="display: none;">
          <div class="progress">
              <div id="progress-bar" class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" aria-valuenow="0"aria-valuemin="0" aria-valuemax="100" style="width: 0%">0%</div>
          </div>

      </div>
  </div>

</div>
  {% endblock content %}

{% block script %}
<script>
    $('#post-form').on('submit', function(event){
        event.preventDefault();
        $form = $(this)
        var formData = new FormData(this);
        $.ajax({
            xhr : function(){
                var xhr = new window.XMLHttpRequest();
                xhr.upload.addEventListener('progress',function(event){
                    if (event.lengthComputable){
                        var percent = Math.round((event.loaded/event.total)*100);
                        $('.loading-bar').show();
                        $('#post-form').hide();
                        $('#progress-bar').attr('aria-valuenow',percent).css('width',percent+'%').text(percent+'%')
                    }
                });
                return xhr;
            },
            url : "{% url 'accounts:post-update' post.pk %}",
            type : "POST",
            data: formData,
            processData: false,
            contentType: false,
            success : function(json) {
              window.location.href=(json.url);
            },

            error : function(xhr,errmsg,err) {
            }
        });
    });

</script>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

<div class="container">
<div class="row align-items-center justify-content-center">
<div class="col-md-5 col-md-offset-3">
  <h1>Sign Up</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Sign Up" class="btn btn-primary">
  </form>

</div>
</div>
</div>

{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title> @{{request.user.username}} profile update</title>{% endblock %}

{% block content %}
<div class="container">
  <div class="content-section">
      <form method="POST" enctype="multipart/form-data" id="user-update-form">
          {% csrf_token %}
          <fieldset class="form-group">
              <div class="profile_update border-bottom">
                  <legend class="mb-3">Update Profile
                  </legend>
              </div>
              {{ User_form|crispy }}
              {{ Profile_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-info btn-sm" type="submit" id="submit-update-btn">Update</button>
          </div>
      </form>
  </div>
</div>

{% endblock content %}

{% block script %}

<script type="text/javascript">
    $(document).ready(function(){
        $('#submit-update-btn').on('click',function(e){
            if ($('#id_username').val()!=="" && $('#id_email').val()!==""){
                $('#loader').show()
            }
            else{
                $('#loader').hide()

            }
        })

    });
</script>
{% endblock %}