accounts/urls.py
from django.urls import re_path, path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r"^login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    re_path(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    re_path(r"^signup/$", views.SignUp.as_view(), name="signup"),
    re_path(r"^home/$", views.home, name=""),
    path('profile-update/',views.updateProfile, name='profile-update'),
    path('follow-unfollow/<int:pk>/',views.userFollowUnfollow, name="follow-unfollow"),
    path('<str:username>/', views.profile, name='profile'),
    path('search/asame/', views.search_view, name='search'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/', views.notifications_update_view, name='notifications-update'),
    path('<str:username>/notifications/count/', views.notifications_unread_count_view, name='notifications-count'),
    path('like/post',views.like_view,name='like'),
    path('p/<slug:slug>/', views.post_detail_view, name="post-detail"),
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'),
]

asame/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^logged/$", views.LoggedPage.as_view(), name="logged"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r'^spotify/', include('spotify.urls', namespace='spotify')),


]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify/urls.py
from django.urls import path
from . import views
from .views import AuthURL, spotify_callback, IsAuthenticated

app_name = "spotify"

urlpatterns = [
    path('', views.photolinks, name='photos'),
    path('search-song', views.searchsong, name='search_song'),
    path('get-auth-url', AuthURL.as_view(), name='connect'),
    path('redirect', spotify_callback, name='redirect'),
    path('is-authenticated', IsAuthenticated.as_view(), name='authenticated'),
]
 # "url": "https://accounts.spotify.com/authorize?scope=user-read-playback-state+user-modify-playback-state+user-read-currently-playing&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fspotify%2Fredirect&client_id=08cb230a331944c7bfa503dfc73dd46c"

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Asame</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Euphoria+Script&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/master.css'%}">

</head>
<body>

  <nav class="navbar  mynav" role="navigation" id="navbar">
    <div class="container">

      <a class="navbar-brand mynav" style="font-size:40px; font-family: 'Euphoria Script', cursive;" href="{% url 'home' %}">Asame</a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'spotify:photos' %}" class="btn btn-simple">Spotify</a></li>
            <li><a class="nav-item nav-link" href="{% url 'accounts:search' %}">Search</a></li>
            <li><a class="nav-item nav-link" href="{% url 'accounts:profile' request.user.username %}">Profile</a></li>
            <li><a class="nav-item nav-link" href="{% url 'accounts:notifications' request.user.username %}">Notification <span class="badge badge-light" style="display: none;" id="notifications-count"></span></a></li>
            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
            <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
          {% endif %}
        </ul>
    </div>
  </nav>



  {% block content %}
  {% endblock %}



  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>

  <script src="{% static 'asame/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'asame/js/infinite.min.js' %}"></script>

  {% block script %}
  {% endblock %}


{% if user.is_authenticated %}

    <script type="text/javascript">
      $(document).ready(function(){

        $.ajax({
                url: "{% url 'accounts:notifications-count' request.user.username %}",
                type: 'get',
                success: function(data){
                  if (data.count===0) {
                    $('#notifications-count').hide()
                    $('#notifications-count-2').hide()
                  }
                  else {
                    $('#notifications-count').show()
                    $('#notifications-count-2').show()
                    $('#notifications-count').text(data.count)
                    $('#notifications-count-2').text(data.count)

                  }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                }
            });
      });
    </script>
    {% endif %}

    <script>

    $(document).ready(function(){

        $("form").attr("enctype","multipart/form-data");

    });

    </script>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}

templates/logged.html
{% extends "base.html" %}
{% block content %}

<br><br><br>
<div class="container" style="text-align:center;">
  <h1>A cat a day, keeps the sorrow away!</h1>
  <br>
  <img src="https://media.tenor.com/images/eff22afc2220e9df92a7aa2f53948f9f/tenor.gif" alt="kitty cat">
</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="text-align:center;">
<h1>Thanks for visiting! Come back soon!</h1>
<img src="https://i.pinimg.com/originals/84/5d/f1/845df1aefc6a5e37ae575327a0cc6e43.gif" alt="">
</div>
{% endblock %}