asame/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^logged/$", views.LoggedPage.as_view(), name="logged"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r'^spotify/', include('spotify.urls', namespace='spotify')),


]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify/urls.py
from django.urls import path
from . import views
from .views import AuthURL, spotify_callback, IsAuthenticated

app_name = "spotify"

urlpatterns = [
    path('', views.photolinks, name='photos'),
    path('search-song', views.searchsong, name='search_song'),
    path('get-auth-url', AuthURL.as_view(), name='connect'),
    path('redirect', spotify_callback, name='redirect'),
    path('is-authenticated', IsAuthenticated.as_view(), name='authenticated'),
]
 # "url": "https://accounts.spotify.com/authorize?scope=user-read-playback-state+user-modify-playback-state+user-read-currently-playing&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fspotify%2Fredirect&client_id=08cb230a331944c7bfa503dfc73dd46c"

spotify/models.py
from django.db import models


# Create your models here.
class SpotifyToken(models.Model):
    user = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    refresh_token = models.CharField(max_length=150)
    access_token = models.CharField(max_length=150)
    expires_in = models.DateTimeField()
    token_type = models.CharField(max_length=50)

spotify/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .credentials import REDIRECT_URI, CLIENT_SECRET, CLIENT_ID
from rest_framework.views import APIView
from requests import Request, post
from rest_framework import status
from rest_framework.response import Response
from .util import update_or_create_user_tokens, is_spotify_authenticated, get_user_tokens, refresh_spotify_token
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials



def photolinks(request):
    return render(request, "spotify/photolink.html")


def searchsong(request):
    # if request.method=='POST':
    #     artist_uri = request.POST.get('uri')
    #     spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials(client_id=CLIENT_ID,client_secret=CLIENT_SECRET,))
    #     results = spotify.artist_top_tracks(artist_uri)
    #     final_result=results['tracks'][:10]
    #     return render(request,'spotify/search_song.html',{"results":final_result})
    # else:
# for track in results['tracks'][:10]:
#     print('track    : ' + track['name'])
#     print('audio    : ' + track['preview_url'])
#     print('cover art: ' + track['album']['images'][0]['url'])
#     print()
        # return render(request,'spotify/search_song.html',)
    return render(request, "spotify/search_song.html")


class AuthURL(APIView):
    def get(self, request, format=None):
        scopes = 'user-read-playback-state user-modify-playback-state user-read-currently-playing'

        url = Request('GET', 'https://accounts.spotify.com/authorize', params={
            'scope': scopes,
            'response_type': 'code',
            'redirect_uri': REDIRECT_URI,
            'client_id': CLIENT_ID
        }).prepare().url

        return redirect(url)
        # return Response({'url': url}, status=status.HTTP_200_OK)


def spotify_callback(request, format=None):
    code = request.GET.get('code')
    error = request.GET.get('error')

    response = post('https://accounts.spotify.com/api/token', data={
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': REDIRECT_URI,
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET
    }).json()

    access_token = response.get('access_token')
    token_type = response.get('token_type')
    refresh_token = response.get('refresh_token')
    expires_in = response.get('expires_in')
    error = response.get('error')

    if not request.session.exists(request.session.session_key):
        request.session.create()

    update_or_create_user_tokens(
        request.session.session_key, access_token, token_type, expires_in, refresh_token)

    # return redirect('http://127.0.0.1:8000/spotify/redirect.html')
    return render(request, 'spotify/redirect.html')


class IsAuthenticated(APIView):
    def get(self, request, format=None):
        is_authenticated = is_spotify_authenticated(
            self.request.session.session_key)
        return Response({'status': is_authenticated}, status=status.HTTP_200_OK)

spotify/templates/spotify/photolink.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}


<br><br><br><br><br><br>

<div class="container">
  <h1>Hello this is spotify testing</h1>
  <a href="{% url 'spotify:connect' %}" class="btn btn-primary">Connect with spotify</a>

</div>


{% endblock %}

spotify/templates/spotify/redirect.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}


<br><br><br><br><br><br>

<div class="container">
  <h1>You are connected to spotify!</h1>
  <h2>Nice, now go to pick your song!</h2>
  <a href="{% url 'spotify:search_song' %}" class="btn btn-primary">Search</a>





{% endblock %}

spotify/templates/spotify/search_song.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}


<br><br><br><br><br><br>

<div class="container">
  <h1>Pick your tracks :)</h1>

  <form method="post">
    {% csrf_token %}
    <div class="form-group row">
      <label for="colform" class="col-sm-2 col-form-label col-form-label-lg">Search for a song</label>
      <div class="col-sm-10">
        <input type="" name="uri" placeholder="type uri" class="form-control form-control-lg" id="colform">
        <br>
        <button type="submit" class="btn btn-success btn-lg mt-1" name="button">Submit</button>

      </div>

    </div>
  </form>
</div>



{% if results %}
  <div class="container bg-dark p-2">
    {% for x in results %}
      <ol class="list-group mt-1">
        <li class="list-group-item bg-info text-center"><h3 class="text-white" >{{x.name}}</h3></li>
        <li class="list-group-item" ><a href='{{x.preview_url}}'><button type="button" class="btn btn-success btn-lg mt-1">PLAY SONG</button></a></li>
        <li class="list-group-item"><img src="{{x.album.images.0.url}}" style="width=10px; height=10px;" class="" alt=""></li>
      </ol><hr>
    {% endfor %}
  </div>

{% endif %}





{% endblock %}